import Mathlib.Tactic.Recall
import Mathlib.RingTheory.DiscreteValuationRing.Basic
import Mathlib.RingTheory.Valuation.Discrete.Basic

/-!
## Discussion following Definition 1.11 — Uniformizers, PID, Ideal Structure in DVRs

Let us suppose that the integral domain `A` is the valuation ring of its fraction field
with respect to some discrete valuation `v`. Any element `π ∈ A` with `v(π) = 1` is called
a *uniformizer*. Every `x ∈ k×` can be written uniquely as `x = uπⁿ` where `n = v(x)` and
`u ∈ A×`. It follows that `A` is a UFD and PID. Every nonzero ideal equals `(πⁿ)` for some
`n ≥ 0`. The ideals are totally ordered, and `𝔪 = (π)` is the unique maximal ideal (and the
only nonzero prime ideal).

### Claims formalized

1. **Uniformizer definition** — `Irreducible ϖ ↔ maximalIdeal R = Ideal.span {ϖ}` (DVR convention)
2. **Unique factorization** `x = uπⁿ` — `IsDiscreteValuationRing.eq_unit_mul_pow_irreducible`
3. **A is a PID and UFD** — instances from `IsDiscreteValuationRing`
4. **Every nonzero ideal = (πⁿ)** — `IsDiscreteValuationRing.ideal_eq_span_pow_irreducible`
5. **Ideals are totally ordered** — `ValuationRing.instLinearOrderIdeal`
6. **Maximal ideal 𝔪 = (π)** is unique maximal and only nonzero prime
-/

section DVRDiscussion

variable {R : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]

/-! ### Claim 1: Uniformizer definition

In Mathlib's DVR setting, a uniformizer is an irreducible element. The key equivalence:
`Irreducible ϖ ↔ maximalIdeal R = Ideal.span {ϖ}`.
-/

/-- An irreducible element of a DVR generates the maximal ideal — this is the
uniformizer characterization. -/
example (ϖ : R) : Irreducible ϖ ↔ IsLocalRing.maximalIdeal R = Ideal.span {ϖ} :=
  IsDiscreteValuationRing.irreducible_iff_uniformizer ϖ

/-- Uniformizers (irreducible elements) exist in a DVR. -/
recall IsDiscreteValuationRing.exists_irreducible
    {R : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R] :
    ∃ ϖ : R, Irreducible ϖ

/-! ### Claim 2: Unique factorization x = uπⁿ

Every nonzero element is a unit times a power of the uniformizer. -/

/-- In a DVR, every nonzero element is associated to a power of the uniformizer. -/
recall IsDiscreteValuationRing.associated_pow_irreducible
    {R : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    {a : R} (ha : a ≠ 0) {ϖ : R} (hirr : Irreducible ϖ) :
    ∃ n : ℕ, Associated a (ϖ ^ n)

/-- The additive valuation of a DVR gives the exponent in the unique factorization. -/
recall IsDiscreteValuationRing.addVal
    (R : Type*) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R] :
    AddValuation R ℕ∞

/-! ### Claim 3: A is a PID and UFD

`IsDiscreteValuationRing` extends `IsPrincipalIdealRing`, and every PID is a UFD. -/

/-- A DVR is a principal ideal ring (by definition). -/
example : IsPrincipalIdealRing R := inferInstance

/-- A DVR is a unique factorization domain (every PID is a UFD). -/
example : UniqueFactorizationMonoid R := inferInstance

/-! ### Claim 4: Every nonzero ideal = (πⁿ)

For a DVR with uniformizer `ϖ`, every nonzero ideal has the form `Ideal.span {ϖ ^ n}`. -/

/-- Every nonzero ideal of a DVR is generated by a power of the uniformizer. -/
recall IsDiscreteValuationRing.ideal_eq_span_pow_irreducible
    {R : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    {s : Ideal R} (hs : s ≠ ⊥) {ϖ : R} (hirr : Irreducible ϖ) :
    ∃ n : ℕ, s = Ideal.span {ϖ ^ n}

/-! ### Claim 5: Ideals are totally ordered

Since a DVR is a valuation ring, its ideals are linearly ordered by inclusion. -/

/-- A DVR is a valuation ring, so its ideals are linearly ordered. -/
example : ValuationRing R := inferInstance

-- The ideals of a valuation ring are totally ordered by inclusion.
example (I J : Ideal R) : I ≤ J ∨ J ≤ I :=
  (ValuationRing.le_total_ideal (A := R)).total I J

/-! ### Claim 6: Maximal ideal 𝔪 = (π) — unique maximal and only nonzero prime

The maximal ideal is generated by the uniformizer. It is the unique nonzero prime ideal. -/

/-- The maximal ideal of a DVR is generated by any uniformizer. -/
theorem maximalIdeal_eq_span_uniformizer (ϖ : R) (hirr : Irreducible ϖ) :
    IsLocalRing.maximalIdeal R = Ideal.span {ϖ} :=
  (IsDiscreteValuationRing.irreducible_iff_uniformizer ϖ).mp hirr

/-- A DVR is characterized as a PID with exactly one nonzero prime ideal. -/
recall IsDiscreteValuationRing.iff_pid_with_one_nonzero_prime
    (R : Type u) [CommRing R] [IsDomain R] :
    IsDiscreteValuationRing R ↔
      IsPrincipalIdealRing R ∧ ∃! P : Ideal R, P ≠ ⊥ ∧ P.IsPrime

/-- Any two irreducible elements of a DVR are associated (i.e., differ by a unit),
confirming that ideals `(πⁿ)` depend only on `n`, not the choice of uniformizer. -/
recall IsDiscreteValuationRing.associated_of_irreducible
    {R : Type*} [CommRing R] [IsDomain R] [IsDiscreteValuationRing R]
    {a b : R} (ha : Irreducible a) (hb : Irreducible b) :
    Associated a b

end DVRDiscussion
