import SutherlandNumberTheoryLecture1Draft2.Chapter1.Definition1_10
import SutherlandNumberTheoryLecture1Draft2.Chapter1.Definition1_13
import Mathlib.RingTheory.Localization.AtPrime.Basic
import Mathlib.RingTheory.LocalRing.ResidueField.Basic
import Mathlib.RingTheory.Ideal.NatInt

/-!
## Example 1.14 — The Ring `ℤ_{(p)}`

**Example 1.14.** For the `p`-adic valuation `vₚ : ℚ → ℤ ∪ {∞}`, the valuation ring is
$$ℤ_{(p)} = \{a/b ∈ ℚ ∣ a, b ∈ ℤ, p ∤ b\},$$
which is the localization of `ℤ` at the prime ideal `(p)`.
The maximal ideal is `𝔪 = (p)` and the residue field is `ℤ_{(p)}/pℤ_{(p)} ≃ 𝔽_p`.

In Mathlib, `ℤ_{(p)}` is the localization `Localization.AtPrime (Ideal.span {(p : ℤ)})`.
The prime ideal `(p)` has `IsPrime` status coming from `p` being prime in `ℤ`.
-/

/-- The prime ideal `(p)` in `ℤ` has the `IsPrime` property when `p` is a prime natural number. -/
theorem primeIdealZ_isPrime (p : ℕ) [hp : Fact p.Prime] :
    (Ideal.span {(p : ℤ)} : Ideal ℤ).IsPrime := by
  rw [Ideal.span_singleton_prime (by exact_mod_cast hp.out.ne_zero)]
  exact Nat.prime_iff_prime_int.mp hp.out

/-- `ℤ_{(p)}` is a local ring with maximal ideal generated by `p` (Example 1.14).
Uses the localization `Localization.AtPrime`. -/
theorem zLocAtP_isLocalRing (p : ℕ) [hp : Fact p.Prime] :
    haveI : (Ideal.span {(p : ℤ)} : Ideal ℤ).IsPrime := primeIdealZ_isPrime p
    IsLocalRing (Localization.AtPrime (Ideal.span {(p : ℤ)})) :=
  inferInstance
